// ─── CONSTANTS ────────────────────────────────────────────────────────────────
export const ALL_DAYS = ['MON','TUE','WED','THU','FRI','SAT','SUN'];

export const CATEGORIES = [
  {value:'work',      label:'Work'},
  {value:'commute',   label:'Commute'},
  {value:'exercise',  label:'Exercise / Walk'},
  {value:'creative',  label:'Creative'},
  {value:'errands',   label:'Errands'},
  {value:'social',    label:'Social'},
  {value:'mealprep',  label:'Meal Prep / Cooking'},
  {value:'selfcare',  label:'Self-Care'},
  {value:'sleep',     label:'Sleep'},
  {value:'papiapt',   label:'Papi Appointments'},
  {value:'taraapt',   label:'Tara Appointments'},
  {value:'cats',      label:'Cats'},
  {value:'other',     label:'Other'},
];

// ─── SCHEDULE DATA ────────────────────────────────────────────────────────────
// Workday morning: 4:30am-8:00am (with commute)
// Nonworkday morning: 4:30am-7:00am (no commute)
// Pre-workday evening: 9:00pm-10:30pm
// Pre-nonworkday evening: 10:00pm-11:30pm
export const BASE = {
  w1: {
    MON:[
      {s:'00:00',e:'04:30',c:'sleep',l:'Sleep'},
      {s:'04:30',e:'05:00',c:'selfcare',l:'Sunrise alarm + birds'},
      {s:'05:00',e:'05:30',c:'exercise',l:'Stationary bike'},
      {s:'05:30',e:'06:00',c:'selfcare',l:'Get ready'},
      {s:'06:00',e:'06:30',c:'selfcare',l:'Coffee + light therapy + admin'},
      {s:'06:30',e:'07:00',c:'selfcare',l:'Final prep + cats'},
      {s:'07:00',e:'08:00',c:'commute',l:'Commute in'},
      {s:'08:00',e:'15:30',c:'work',l:'Work',n:'7 hrs'},
      {s:'15:30',e:'16:45',c:'commute',l:'Commute home'},
      {s:'17:00',e:'17:20',c:'selfcare',l:'Decompress'},
      {s:'17:30',e:'18:15',c:'exercise',l:'Walk'},
      {s:'18:30',e:'19:15',c:'mealprep',l:'Cook / heat prep'},
      {s:'19:30',e:'21:00',c:'social',l:'Free / Greg time'},
      {s:'21:00',e:'22:30',c:'selfcare',l:'Evening routine',n:'Shower, tea, wind down'},
    ],
    TUE:[
      {s:'00:00',e:'04:30',c:'sleep',l:'Sleep'},
      {s:'04:30',e:'05:00',c:'selfcare',l:'Sunrise alarm + birds'},
      {s:'05:00',e:'05:30',c:'exercise',l:'Stationary bike'},
      {s:'05:30',e:'06:00',c:'selfcare',l:'Get ready'},
      {s:'06:00',e:'06:30',c:'selfcare',l:'Coffee + light therapy + admin'},
      {s:'06:30',e:'07:00',c:'selfcare',l:'Final prep + cats'},
      {s:'07:00',e:'08:00',c:'commute',l:'Commute in'},
      {s:'08:00',e:'15:30',c:'work',l:'Work',n:'7 hrs'},
      {s:'15:30',e:'16:45',c:'commute',l:'Commute home'},
      {s:'17:00',e:'17:20',c:'selfcare',l:'Decompress'},
      {s:'17:30',e:'18:15',c:'exercise',l:'Walk'},
      {s:'18:30',e:'19:15',c:'mealprep',l:'Cook / heat prep'},
      {s:'19:30',e:'21:00',c:'creative',l:'Game design or painting'},
      {s:'21:00',e:'22:30',c:'selfcare',l:'Evening routine',n:'Shower, tea, wind down'},
    ],
    WED:[
      {s:'00:00',e:'04:30',c:'sleep',l:'Sleep'},
      {s:'04:30',e:'05:00',c:'selfcare',l:'Sunrise alarm + birds'},
      {s:'05:00',e:'05:30',c:'exercise',l:'Stationary bike'},
      {s:'05:30',e:'06:00',c:'selfcare',l:'Get ready'},
      {s:'06:00',e:'06:30',c:'selfcare',l:'Coffee + light therapy + admin'},
      {s:'06:30',e:'07:00',c:'selfcare',l:'Final prep + cats'},
      {s:'07:00',e:'08:00',c:'commute',l:'Commute in'},
      {s:'08:00',e:'15:30',c:'work',l:'Work',n:'7 hrs'},
      {s:'15:30',e:'16:45',c:'commute',l:'Commute home'},
      {s:'17:00',e:'17:20',c:'selfcare',l:'Decompress'},
      {s:'17:30',e:'18:30',c:'errands',l:'Admin block',n:'Tracking, health, cat chart'},
      {s:'18:30',e:'19:15',c:'mealprep',l:'Cook / heat prep'},
      {s:'19:30',e:'21:00',c:'social',l:'Gaming w/ friends (optional)'},
      {s:'21:00',e:'22:30',c:'selfcare',l:'Evening routine',n:'Shower, tea, wind down'},
    ],
    THU:[
      {s:'00:00',e:'04:30',c:'sleep',l:'Sleep'},
      {s:'04:30',e:'05:00',c:'selfcare',l:'Sunrise alarm + birds'},
      {s:'05:00',e:'05:30',c:'exercise',l:'Stationary bike'},
      {s:'05:30',e:'06:00',c:'selfcare',l:'Get ready'},
      {s:'06:00',e:'06:30',c:'selfcare',l:'Coffee + light therapy + admin'},
      {s:'06:30',e:'07:00',c:'selfcare',l:'Final prep + cats'},
      {s:'07:00',e:'08:00',c:'commute',l:'Commute in'},
      {s:'08:00',e:'19:00',c:'work',l:'Long day',n:'10.5 hrs'},
      {s:'19:00',e:'20:15',c:'commute',l:'Commute home'},
      {s:'20:15',e:'21:00',c:'selfcare',l:'Recovery',n:'Thu night protected'},
      {s:'21:00',e:'22:30',c:'selfcare',l:'Evening routine',n:'Shower, tea, wind down'},
    ],
    FRI:[
      {s:'00:00',e:'04:30',c:'sleep',l:'Sleep'},
      {s:'04:30',e:'05:00',c:'selfcare',l:'Sunrise alarm + birds'},
      {s:'05:00',e:'05:30',c:'exercise',l:'Stationary bike'},
      {s:'05:30',e:'06:00',c:'selfcare',l:'Get ready'},
      {s:'06:00',e:'06:30',c:'selfcare',l:'Coffee + light therapy + admin'},
      {s:'06:30',e:'07:00',c:'selfcare',l:'Final prep + cats'},
      {s:'07:00',e:'08:00',c:'commute',l:'Commute in'},
      {s:'08:00',e:'15:30',c:'work',l:'Work',n:'7 hrs'},
      {s:'15:30',e:'16:45',c:'commute',l:'Commute home'},
      {s:'17:00',e:'17:20',c:'selfcare',l:'Decompress'},
      {s:'17:30',e:'18:30',c:'exercise',l:'Walk'},
      {s:'18:30',e:'19:15',c:'mealprep',l:'Cook / heat prep'},
      {s:'19:30',e:'22:00',c:'social',l:'Social / free evening'},
      {s:'22:00',e:'23:30',c:'selfcare',l:'Evening routine',n:'Shower, tea, wind down'},
    ],
    SAT:[
      {s:'00:00',e:'04:30',c:'sleep',l:'Sleep'},
      {s:'04:30',e:'05:00',c:'selfcare',l:'Sunrise alarm + birds'},
      {s:'05:00',e:'05:30',c:'exercise',l:'Stationary bike'},
      {s:'05:30',e:'06:00',c:'selfcare',l:'Get ready'},
      {s:'06:00',e:'06:30',c:'selfcare',l:'Coffee + light therapy + admin'},
      {s:'06:30',e:'07:00',c:'selfcare',l:'Final prep + cats'},
      {s:'07:00',e:'09:00',c:'errands',l:'Apartment pickup',n:'2hr reset'},
      {s:'09:00',e:'10:00',c:'selfcare',l:'Breakfast + light therapy'},
      {s:'10:00',e:'13:00',c:'creative',l:'Art / painting',n:'Dedicated art time'},
      {s:'13:00',e:'14:00',c:'other',l:'Lunch + break'},
      {s:'14:00',e:'17:00',c:'creative',l:'Tabletop game design',n:'Game dev block'},
      {s:'17:00',e:'22:00',c:'social',l:'Social (W1 social Sat)',n:'Flexible'},
      {s:'22:00',e:'23:30',c:'selfcare',l:'Evening routine',n:'Shower, tea, wind down'},
    ],
    SUN:[
      {s:'00:00',e:'04:30',c:'sleep',l:'Sleep'},
      {s:'04:30',e:'05:00',c:'selfcare',l:'Sunrise alarm + birds'},
      {s:'05:00',e:'05:30',c:'exercise',l:'Stationary bike'},
      {s:'05:30',e:'06:00',c:'selfcare',l:'Get ready'},
      {s:'06:00',e:'06:30',c:'selfcare',l:'Coffee + light therapy + admin'},
      {s:'06:30',e:'07:00',c:'selfcare',l:'Final prep + cats'},
      {s:'07:00',e:'09:00',c:'errands',l:'Apartment pickup',n:'2hr reset'},
      {s:'09:00',e:'09:30',c:'errands',l:'Weekly planning + reset checklist'},
      {s:'09:30',e:'10:00',c:'selfcare',l:'Breakfast + light therapy'},
      {s:'10:00',e:'16:00',c:'mealprep',l:'Meal prep',n:'6hr block'},
      {s:'16:00',e:'18:00',c:'creative',l:'Creative time'},
      {s:'18:00',e:'20:00',c:'social',l:'Greg time'},
      {s:'21:00',e:'22:30',c:'selfcare',l:'Evening routine',n:'Shower, tea, wind down'},
    ],
  },
  w2: {
    MON:[
      {s:'00:00',e:'04:30',c:'sleep',l:'Sleep'},
      {s:'04:30',e:'05:00',c:'selfcare',l:'Sunrise alarm + birds'},
      {s:'05:00',e:'05:30',c:'exercise',l:'Stationary bike'},
      {s:'05:30',e:'06:00',c:'selfcare',l:'Get ready'},
      {s:'06:00',e:'06:30',c:'selfcare',l:'Coffee + light therapy + admin'},
      {s:'06:30',e:'07:00',c:'selfcare',l:'Final prep + cats'},
      {s:'07:00',e:'08:00',c:'commute',l:'Commute in'},
      {s:'08:00',e:'15:30',c:'work',l:'Work',n:'7 hrs'},
      {s:'15:30',e:'16:45',c:'commute',l:'Commute home'},
      {s:'17:00',e:'17:20',c:'selfcare',l:'Decompress'},
      {s:'17:30',e:'18:15',c:'exercise',l:'Walk'},
      {s:'18:30',e:'19:15',c:'mealprep',l:'Cook / heat prep'},
      {s:'19:30',e:'21:00',c:'creative',l:'Game design or painting'},
      {s:'21:00',e:'22:30',c:'selfcare',l:'Evening routine',n:'Shower, tea, wind down'},
    ],
    TUE:[
      {s:'00:00',e:'04:30',c:'sleep',l:'Sleep'},
      {s:'04:30',e:'05:00',c:'selfcare',l:'Sunrise alarm + birds'},
      {s:'05:00',e:'05:30',c:'exercise',l:'Stationary bike'},
      {s:'05:30',e:'06:00',c:'selfcare',l:'Get ready'},
      {s:'06:00',e:'06:30',c:'selfcare',l:'Coffee + light therapy + admin'},
      {s:'06:30',e:'07:00',c:'selfcare',l:'Final prep + cats'},
      {s:'07:00',e:'08:00',c:'commute',l:'Commute in'},
      {s:'08:00',e:'15:30',c:'work',l:'Work',n:'7 hrs'},
      {s:'15:30',e:'16:45',c:'commute',l:'Commute home'},
      {s:'17:00',e:'17:20',c:'selfcare',l:'Decompress'},
      {s:'17:30',e:'18:15',c:'exercise',l:'Walk'},
      {s:'18:30',e:'19:15',c:'mealprep',l:'Cook / heat prep'},
      {s:'19:30',e:'21:00',c:'errands',l:'Admin / appts / tracking'},
      {s:'21:00',e:'22:30',c:'selfcare',l:'Evening routine',n:'Shower, tea, wind down'},
    ],
    WED:[
      {s:'00:00',e:'04:30',c:'sleep',l:'Sleep'},
      {s:'04:30',e:'05:00',c:'selfcare',l:'Sunrise alarm + birds'},
      {s:'05:00',e:'05:30',c:'exercise',l:'Stationary bike'},
      {s:'05:30',e:'06:00',c:'selfcare',l:'Get ready'},
      {s:'06:00',e:'06:30',c:'selfcare',l:'Coffee + light therapy + admin'},
      {s:'06:30',e:'07:00',c:'selfcare',l:'Final prep + cats'},
      {s:'07:00',e:'08:00',c:'commute',l:'Commute in'},
      {s:'08:00',e:'15:30',c:'work',l:'Work',n:'7 hrs'},
      {s:'15:30',e:'16:45',c:'commute',l:'Commute home'},
      {s:'17:00',e:'17:20',c:'selfcare',l:'Decompress'},
      {s:'17:30',e:'18:30',c:'exercise',l:'Walk'},
      {s:'18:30',e:'19:15',c:'mealprep',l:'Cook / heat prep'},
      {s:'19:30',e:'21:00',c:'social',l:'Gaming w/ friends (optional)'},
      {s:'21:00',e:'22:30',c:'selfcare',l:'Evening routine',n:'Shower, tea, wind down'},
    ],
    THU:[
      {s:'00:00',e:'04:30',c:'sleep',l:'Sleep'},
      {s:'04:30',e:'05:00',c:'selfcare',l:'Sunrise alarm + birds'},
      {s:'05:00',e:'05:30',c:'exercise',l:'Stationary bike'},
      {s:'05:30',e:'06:00',c:'selfcare',l:'Get ready'},
      {s:'06:00',e:'06:30',c:'selfcare',l:'Coffee + light therapy + admin'},
      {s:'06:30',e:'07:00',c:'selfcare',l:'Final prep + cats'},
      {s:'07:00',e:'08:00',c:'commute',l:'Commute in'},
      {s:'08:00',e:'19:00',c:'work',l:'Long day',n:'10.5 hrs'},
      {s:'19:00',e:'20:15',c:'commute',l:'Commute home'},
      {s:'20:15',e:'22:00',c:'selfcare',l:'Recovery',n:'Thu night protected'},
      {s:'22:00',e:'23:30',c:'selfcare',l:'Evening routine',n:'Shower, tea, wind down'},
    ],
    FRI:[
      {s:'00:00',e:'04:30',c:'sleep',l:'Sleep'},
      {s:'04:30',e:'05:00',c:'selfcare',l:'Sunrise alarm + birds'},
      {s:'05:00',e:'05:30',c:'exercise',l:'Stationary bike'},
      {s:'05:30',e:'06:00',c:'selfcare',l:'Get ready'},
      {s:'06:00',e:'06:30',c:'selfcare',l:'Coffee + light therapy + admin'},
      {s:'06:30',e:'07:00',c:'selfcare',l:'Final prep + cats'},
      {s:'07:00',e:'09:00',c:'errands',l:'Apartment pickup',n:'2hr reset'},
      {s:'09:00',e:'11:00',c:'errands',l:'Admin anchor block',n:'Taxes, health tracker, forms'},
      {s:'11:00',e:'12:30',c:'selfcare',l:'Self-care / errands'},
      {s:'12:30',e:'15:00',c:'other',l:'Free / errands / backlog task'},
      {s:'15:00',e:'17:00',c:'creative',l:'Creative time'},
      {s:'17:00',e:'18:30',c:'exercise',l:'Afternoon walk'},
      {s:'19:00',e:'22:00',c:'social',l:'Social / free evening'},
      {s:'22:00',e:'23:30',c:'selfcare',l:'Evening routine',n:'Shower, tea, wind down'},
    ],
    SAT:[
      {s:'00:00',e:'04:30',c:'sleep',l:'Sleep'},
      {s:'04:30',e:'05:00',c:'selfcare',l:'Sunrise alarm + birds'},
      {s:'05:00',e:'05:30',c:'exercise',l:'Stationary bike'},
      {s:'05:30',e:'06:00',c:'selfcare',l:'Get ready'},
      {s:'06:00',e:'06:30',c:'selfcare',l:'Coffee + light therapy + admin'},
      {s:'06:30',e:'07:00',c:'selfcare',l:'Final prep + cats'},
      {s:'07:00',e:'09:00',c:'errands',l:'Apartment pickup',n:'2hr reset'},
      {s:'09:00',e:'10:00',c:'selfcare',l:'Breakfast + light therapy'},
      {s:'10:00',e:'13:00',c:'creative',l:'Art / painting',n:'Dedicated art time'},
      {s:'13:00',e:'14:00',c:'other',l:'Lunch + break'},
      {s:'14:00',e:'17:00',c:'creative',l:'Tabletop game design',n:'Game dev block'},
      {s:'17:00',e:'22:00',c:'social',l:'Social (W2 social Sat)',n:'Bi-weekly social Saturday'},
      {s:'22:00',e:'23:30',c:'selfcare',l:'Evening routine',n:'Shower, tea, wind down'},
    ],
    SUN:[
      {s:'00:00',e:'04:30',c:'sleep',l:'Sleep'},
      {s:'04:30',e:'05:00',c:'selfcare',l:'Sunrise alarm + birds'},
      {s:'05:00',e:'05:30',c:'exercise',l:'Stationary bike'},
      {s:'05:30',e:'06:00',c:'selfcare',l:'Get ready'},
      {s:'06:00',e:'06:30',c:'selfcare',l:'Coffee + light therapy + admin'},
      {s:'06:30',e:'07:00',c:'selfcare',l:'Final prep + cats'},
      {s:'07:00',e:'09:00',c:'errands',l:'Apartment pickup',n:'2hr reset'},
      {s:'09:00',e:'09:30',c:'errands',l:'Weekly planning + reset checklist'},
      {s:'09:30',e:'10:00',c:'selfcare',l:'Breakfast + light therapy'},
      {s:'10:00',e:'16:00',c:'mealprep',l:'Meal prep',n:'6hr block'},
      {s:'16:00',e:'18:00',c:'creative',l:'Creative time'},
      {s:'18:00',e:'20:00',c:'social',l:'Greg time'},
      {s:'21:00',e:'22:30',c:'selfcare',l:'Evening routine',n:'Shower, tea, wind down'},
    ],
  }
};

// Assign stable _id to every BASE block
let _idCounter = 0;
for (const week of Object.keys(BASE)) {
  for (const day of ALL_DAYS) {
    if (BASE[week][day]) {
      BASE[week][day].forEach(b => { b._id = `base_${_idCounter++}`; });
    }
  }
}

export const SMART_TASKS = [
  {id:'s1',name:'CCM certified case manager exam — study + schedule test',cat:'Admin/Career'},
  {id:'s2',name:'Start career planning trajectory',cat:'Career'},
  {id:'s3',name:'Organize Google Drive',cat:'Admin'},
  {id:'s4',name:'Call Ms. Ferrara',cat:'Admin'},
];

export const ASMR_TASKS = [
  {id:'a1',name:'Make Greek yogurt calzone',cat:'Fun/Cooking'},
  {id:'a2',name:'Fix ceramic Xmas tree',cat:'Home'},
  {id:'a3',name:'Make tapioca pudding',cat:'Fun/Cooking'},
  {id:'a4',name:'Make Greek yogurt bread',cat:'Fun/Cooking'},
  {id:'a5',name:'Fill out UPSE reimbursement doctor forms',cat:'Admin'},
  {id:'a6',name:'Start cat health chart',cat:'Cat Care'},
  {id:'a7',name:"Update Ruby's chip",cat:'Cat Care'},
  {id:'a8',name:'Visitor game card ideas',cat:'Creative/Game'},
  {id:'a9',name:'Re-record One Night Osama',cat:'Creative/Game'},
  {id:'a10',name:'Update my health tracker',cat:'Admin/Health'},
  {id:'a11',name:"Update Papi's health tracker",cat:'Admin/Health'},
  {id:'a12',name:'Re-sisal cat trees',cat:'Cat Care'},
];

export const WEEKLY_RESET = [
  {section:'Bedroom',items:['Pick up bedroom','Put away laundry','Pick up desk','Change sheets/pillowcases']},
  {section:'Bathroom',items:['Wipe down sink/counter','Clean toilet','Mop/wipe floor','Replace towels']},
  {section:'Kitchen',items:['Wipe down counters','Clean stovetop','Wipe microwave','Take out trash','Mop floor']},
  {section:'Dining Room',items:['Clear table','Wipe down table','Chairs/floor check']},
  {section:'Living Room',items:['Pick up clutter','Vacuum/sweep','Dust surfaces']},
  {section:'Cats',items:['Clean all litter boxes','Wipe litter area','Refill food/water stations','Check cat health notes']},
  {section:'Meal Prep',items:['Meal prep complete']},
];

export const RESET_IDS = WEEKLY_RESET.flatMap(s => s.items.map((_, i) => `${s.section}-${i}`));
